version: 2

sources:
  - name: btc
    description: "Bitcoin data from AWS' public repository"
    database: btc
    schema: btc_schema
    tables:
      - name: btc
        freshness:
          warn_after:
            count: 1
            period: hour
        loaded_at_field: BLOCK_TIMESTAMP